//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.30 at 01:45:58 PM CET 
//


package nl.scholtens.material.sources;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.scholtens.material.sources package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PlanLclistLcCvbyte_QNAME = new QName("", "cvbyte");
    private final static QName _PlanLclistLcBbt_QNAME = new QName("", "bbt");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.scholtens.material.sources
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Plan }
     * 
     */
    public Plan createPlan() {
        return new Plan();
    }

    /**
     * Create an instance of {@link Plan.Operatorlist }
     * 
     */
    public Plan.Operatorlist createPlanOperatorlist() {
        return new Plan.Operatorlist();
    }

    /**
     * Create an instance of {@link Plan.Carlist }
     * 
     */
    public Plan.Carlist createPlanCarlist() {
        return new Plan.Carlist();
    }

    /**
     * Create an instance of {@link Plan.Lclist }
     * 
     */
    public Plan.Lclist createPlanLclist() {
        return new Plan.Lclist();
    }

    /**
     * Create an instance of {@link Plan.Lclist.Lc }
     * 
     */
    public Plan.Lclist.Lc createPlanLclistLc() {
        return new Plan.Lclist.Lc();
    }

    /**
     * Create an instance of {@link Fundef }
     * 
     */
    public Fundef createFundef() {
        return new Fundef();
    }

    /**
     * Create an instance of {@link Plan.Operatorlist.Operator }
     * 
     */
    public Plan.Operatorlist.Operator createPlanOperatorlistOperator() {
        return new Plan.Operatorlist.Operator();
    }

    /**
     * Create an instance of {@link Plan.Carlist.Car }
     * 
     */
    public Plan.Carlist.Car createPlanCarlistCar() {
        return new Plan.Carlist.Car();
    }

    /**
     * Create an instance of {@link Plan.Lclist.Lc.Cvbyte }
     * 
     */
    public Plan.Lclist.Lc.Cvbyte createPlanLclistLcCvbyte() {
        return new Plan.Lclist.Lc.Cvbyte();
    }

    /**
     * Create an instance of {@link Plan.Lclist.Lc.Bbt }
     * 
     */
    public Plan.Lclist.Lc.Bbt createPlanLclistLcBbt() {
        return new Plan.Lclist.Lc.Bbt();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Plan.Lclist.Lc.Cvbyte }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cvbyte", scope = Plan.Lclist.Lc.class)
    public JAXBElement<Plan.Lclist.Lc.Cvbyte> createPlanLclistLcCvbyte(Plan.Lclist.Lc.Cvbyte value) {
        return new JAXBElement<Plan.Lclist.Lc.Cvbyte>(_PlanLclistLcCvbyte_QNAME, Plan.Lclist.Lc.Cvbyte.class, Plan.Lclist.Lc.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Plan.Lclist.Lc.Bbt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "bbt", scope = Plan.Lclist.Lc.class)
    public JAXBElement<Plan.Lclist.Lc.Bbt> createPlanLclistLcBbt(Plan.Lclist.Lc.Bbt value) {
        return new JAXBElement<Plan.Lclist.Lc.Bbt>(_PlanLclistLcBbt_QNAME, Plan.Lclist.Lc.Bbt.class, Plan.Lclist.Lc.class, value);
    }

}
